// GENERATED by docs/risk/generate-world-map-asset.cjs — do not edit
// Territory → label anchor in the risk-world-map.svg coordinate space
// (viewBox 0 0 749.81909 519.06781). Shared by the TV map; regen via the script.
export interface MapAnchor { x: number; y: number; lines: string[] }
export const MAP_VIEWBOX = { w: 749.81909, h: 519.06781 } as const;
export const MAP_ANCHORS: Record<string, MapAnchor> = {
 "Alaska": {
  "x": 57.9,
  "y": 89.4,
  "lines": [
   "Alaska"
  ]
 },
 "Alberta": {
  "x": 116.9,
  "y": 121.3,
  "lines": [
   "Alberta"
  ]
 },
 "Northwest Territory": {
  "x": 137.9,
  "y": 71.5,
  "lines": [
   "Northwest",
   "Territory"
  ]
 },
 "Ontario": {
  "x": 172.4,
  "y": 135.7,
  "lines": [
   "Ontario"
  ]
 },
 "Quebec": {
  "x": 219.9,
  "y": 130.5,
  "lines": [
   "Quebec"
  ]
 },
 "Western United States": {
  "x": 124,
  "y": 179.6,
  "lines": [
   "Western",
   "United States"
  ]
 },
 "Eastern United States": {
  "x": 179.7,
  "y": 187.2,
  "lines": [
   "Eastern",
   "United States"
  ]
 },
 "Central America": {
  "x": 126.2,
  "y": 241.6,
  "lines": [
   "Central",
   "America"
  ]
 },
 "Greenland": {
  "x": 256.3,
  "y": 66.7,
  "lines": [
   "Greenland"
  ]
 },
 "Iceland": {
  "x": 322.1,
  "y": 105.4,
  "lines": [
   "Iceland"
  ]
 },
 "Great Britain": {
  "x": 307.2,
  "y": 156.4,
  "lines": [
   "Great",
   "Britain"
  ]
 },
 "Scandinavia": {
  "x": 381.3,
  "y": 103.9,
  "lines": [
   "Scandinavia"
  ]
 },
 "Northern Europe": {
  "x": 375.1,
  "y": 168,
  "lines": [
   "Northern",
   "Europe"
  ]
 },
 "Western Europe": {
  "x": 325.3,
  "y": 222.7,
  "lines": [
   "Western",
   "Europe"
  ]
 },
 "Southern Europe": {
  "x": 380.6,
  "y": 218.5,
  "lines": [
   "Southern",
   "Europe"
  ]
 },
 "Ukraine": {
  "x": 446.4,
  "y": 148.9,
  "lines": [
   "Ukraine"
  ]
 },
 "Ural": {
  "x": 521.2,
  "y": 114.3,
  "lines": [
   "Ural"
  ]
 },
 "Siberia": {
  "x": 549.1,
  "y": 101.6,
  "lines": [
   "Siberia"
  ]
 },
 "Irkutsk": {
  "x": 602.3,
  "y": 126.1,
  "lines": [
   "Irkutsk"
  ]
 },
 "Yakutsk": {
  "x": 609.2,
  "y": 71.2,
  "lines": [
   "Yakutsk"
  ]
 },
 "Kamchatka": {
  "x": 670,
  "y": 111.4,
  "lines": [
   "Kamchatka"
  ]
 },
 "Mongolia": {
  "x": 611.8,
  "y": 171.4,
  "lines": [
   "Mongolia"
  ]
 },
 "China": {
  "x": 587.2,
  "y": 217.2,
  "lines": [
   "China"
  ]
 },
 "Siam": {
  "x": 602.7,
  "y": 289.2,
  "lines": [
   "Siam"
  ]
 },
 "India": {
  "x": 544.1,
  "y": 274,
  "lines": [
   "India"
  ]
 },
 "Afghanistan": {
  "x": 500.8,
  "y": 189.3,
  "lines": [
   "Afghanistan"
  ]
 },
 "Middle East": {
  "x": 457.6,
  "y": 274.9,
  "lines": [
   "Middle East"
  ]
 },
 "Egypt": {
  "x": 405.8,
  "y": 288.8,
  "lines": [
   "Egypt"
  ]
 },
 "North Africa": {
  "x": 356.1,
  "y": 309.5,
  "lines": [
   "North Africa"
  ]
 },
 "East Africa": {
  "x": 444.4,
  "y": 362.9,
  "lines": [
   "East Africa"
  ]
 },
 "Congo": {
  "x": 403.7,
  "y": 373.5,
  "lines": [
   "Congo"
  ]
 },
 "South Africa": {
  "x": 416.3,
  "y": 434.2,
  "lines": [
   "South Africa"
  ]
 },
 "Venezuela": {
  "x": 192.5,
  "y": 285.7,
  "lines": [
   "Venezuela"
  ]
 },
 "Peru": {
  "x": 186.3,
  "y": 340.2,
  "lines": [
   "Peru"
  ]
 },
 "Brazil": {
  "x": 221.9,
  "y": 343,
  "lines": [
   "Brazil"
  ]
 },
 "Argentina": {
  "x": 202.3,
  "y": 419.1,
  "lines": [
   "Argentina"
  ]
 },
 "Indonesia": {
  "x": 610.8,
  "y": 364.5,
  "lines": [
   "Indonesia"
  ]
 },
 "New Guinea": {
  "x": 675.6,
  "y": 346.8,
  "lines": [
   "New Guinea"
  ]
 },
 "Western Australia": {
  "x": 655,
  "y": 434.5,
  "lines": [
   "Western",
   "Australia"
  ]
 },
 "Eastern Australia": {
  "x": 697.9,
  "y": 429.6,
  "lines": [
   "Eastern",
   "Australia"
  ]
 }
};
